name: Publish package to the Maven Central Repository
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3 #Set up JDK 11, as well as Maven Central Repository credentials and GPG keys
        with:
          java-version: '11'
          distribution: 'adopt' # Available distributions found here: https://github.com/actions/setup-java#supported-distributions
          server-id: ossrh # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: MAVEN_USERNAME # Env var that holds your OSSRH username
          server-password: MAVEN_PASSWORD # Env var that holds your OSSRH password
          gpg-private-key: GPG_PRIVATE_KEY # Env var that holds your GPG private key
          gpg-passphrase: GPG_PASSPHRASE # Env var that holds your GPG passphrase
      - name: Publish package
        run: |
          # -U force updates just to make sure we are using latest dependencies
          # -B Batch mode (do not ask for user input), just in case
          # -P activate profile
          mvn -U -B clean deploy -P release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}